name: Build and Push Docker Image
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  generate-sbom:
    name: Generate SBOM and Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install NPM dependencies
        run: npm install
      - name: Generate SBOM for Javascript
        uses: anchore/sbom-action@v0
        with:
          format: json
          artifact-name: sbom-node-js.json
      - name: Build Docker Image
        run: docker build -t my-node-app:latest .
      - name: Generate SBOM for Docker image
        uses: anchore/sbom-action@v0
        with:
          image: my-node-app:latest
          format: json
          artifact-name: sbom-docker-image.json
      - name: List generated files
        run: ls -la
      - name: Upload SBOMs
        uses: actions/upload-artifact@v3
        with:
          name: sbom-artifacts
          path: |
            sbom-node-js.json
            sbom-docker-image.json